name: PR Tests

on:
  pull_request:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install -r backend/requirements-dev.txt

      - name: Run tests
        run: pytest
